version: '3.8'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/recipe-db
      - SECRET_KEY=dev_secret_key
    depends_on:
      - db
    restart: always
    volumes:
      - ./:/app
    
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=recipe-db
    ports:
      - "5432:5432"

volumes:
  postgres_data:
